# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CACERTS = struct(
    revision = "20181212",
    sha256 = "3346d5dd66ecfeeb9f61bec7ae058cf45d6cee5b51f0722e89ed2f91b171312a",
)

CACERTS = struct(
    revision = "20181212",
    sha256 = "3346d5dd66ecfeeb9f61bec7ae058cf45d6cee5b51f0722e89ed2f91b171312a",
)

CACERTS = struct(
    revision = "20181212",
    sha256 = "3346d5dd66ecfeeb9f61bec7ae058cf45d6cee5b51f0722e89ed2f91b171312a",
)

CACERTS = struct(
    revision = "20181212",
    sha256 = "3346d5dd66ecfeeb9f61bec7ae058cf45d6cee5b51f0722e89ed2f91b171312a",
)

