# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly

# Bazel release installer.
BAZEL_INSTALLER = struct(
    revision = "0.21.0",
    sha256 = "328d5fa87a61e1f6e674a8f88c5ae54b8987eaf5a6c944257600c5029c8feef8",
)

# The Debian packages tarball pulled from the GCS bucket required for the Ubuntu1604 Bazel layer.
DEBS_TARBALL = struct(
    revision = "20181217",
    sha256 = "ff7d57df77b84562cd04192d0f692cae9f7f6b4d2b22ec3c29e0104da3ffaf11",
)

