# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CLANG_INSTALLER = struct(
    revision = "r346485",
    sha256 = "46953316d672669a22a5bca7ccec39b242687bf6bcac3db1d042731de2260844",
)

LIBCXX_INSTALLER = struct(
    revision = "r346485",
    sha256 = "9f494d7aa9ebb7416e585fd0172b3c0af2b56e72346fb120611f3c7497cddd58",
)

DEBS_TARBALL = struct(
    revision = "20181220",
    sha256 = "c30a06a740e9ec4863cd327d035d99502980d31581be7c40d4a433df54dababa",
)

