# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly

# The debian packages tarball pulled from the GCS bucket required for the Ubuntu1604 Python RBE layer.
DEBS_TARBALL = struct(
    revision = "20181218",
    sha256 = "f1b6dea085e374052df9798b49a5d2d2e75c42373f603c6b0c7f31e1b42da2d5",
)

