# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly

BAZEL = struct(
    revision = "0.20.0",
    sha256 = "44aed3bd8e58a889'3445623456eoapuyid7c0cf0696205764e45dec",
)

CLANG = struct(
    revision = "r346485",
    sha256 = "cb23df8c63c40628bdb53de8d542624562456euoa5cdf36857f945a2ea0ec48def92",
)

