RevisionsFilePath: "layers/ubuntu1604/docker/revisions.bzl"
GCSDeps:
  - name: "DEBS_TARBALL"
    description: "The debian packages tarball pulled from the GCS bucket required for the Ubuntu1604 Docker layer."
    bucket: "layer-deps"
    versionRegex: "\\d{8}"
    fileRegex: "^ubuntu1604/docker/debs/\\d{8}_docker_debs\\.tar$"
    startsWith: "ubuntu1604/docker/debs/"
