RevisionsFilePath: "layers/ubuntu1604/docker/revisions.bzl"
GCSDeps:

  # The debian packages tarball pulled from the GCS bucket required for the Ubuntu1604 Docker layer.
  - Name: "DEBS_TARBALL"
    Bucket: "layer-deps"
    VersionRegex: "\\d{8}"
    FileRegex: "^ubuntu1604/docker/debs/\\d{8}_docker_debs\\.tar$"
    StartsWith: "ubuntu1604/docker/debs/"
