# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update serivce and should not be modified directly.

# The debian packages tarball pulled from the GCS bucket required for the Ubuntu1604 Docker layer.
DEBS_TARBALL = struct(
    revision = "20181214",
    sha256 = "cc83d8744fab5f38099d654ab36746b4d87519b146e6871334d21ae0905e86e0",
)

